### ISSUE TITLE
add nginx proxy

### ISSUE THREAD

**Issue by acivitillo** [dyvenia/timeflow#90]
You will need a new container `nginx`. I have done some basic config work already, see below. You will need to configure `nginx.conf` to send traffic to both the frontend and the backend.

nginx.conf
```nginx
server { 
    listen 80;
    server_name frontend;
    root   /usr/share/nginx/html;
    auth_basic           "Administrator’s Area";
    auth_basic_user_file /etc/apache2/.passwords; 
}
```

docker-compose.yaml
```yaml
version: "3"

services:
  client:
    image: nginx
    build: .
    ports:
      - 8000:80
    volumes:
      - ./html:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./.passwords:/etc/apache2/.passwords
```

Dockerfile
```Dockerfile
FROM nginx
COPY ./nginx.conf /etc/nginx/conf.d/default.conf
```

Create hashed passwords
```bash
htpasswd /etc/apache2/.passwords alessio
```

.passwords
```bash
username:encrypted-password:comment
alessio:$apr1$lE4tzWu2$4rQxK/3iSkyAcf.ZPn9aQ1
```
