### ISSUE TITLE
Port stuck on 8000 (Docker)

### ISSUE THREAD

**Issue by liberty-rising** [dyvenia/timeflow#98]
Description: Tried starting docker on another port (8002,8003) without success. Keeps starting on port 8000.

docker-compose.yaml
```yaml
version: '3'
services:
  fastapi:
    image: fastapi:v1
    volumes:
      - ./backend/:/backend/
    command: bash -c "uvicorn backend.main:app --reload --host 0.0.0.0"
    ports:
      - 8003:8003
    container_name: fastapi

  idom:
    image: idom:v1
    volumes:
      - ./frontend/:/frontend/
    command: bash -c "cd frontend && python3 -m run_reload.py"
    ports:
      - 8001:8001
    container_name: idom
```

config.py
`base_url = "http://fastapi:8000"`

**Comment by jkrobicki** [comment]
Solution:

docker-compose.yaml
```yaml
version: '3'
networks:
    static-network:
        ipam:
            driver: default
            config:
                - subnet: 172.28.0.0/16
services:
  fastapi:
    image: fastapi:v1
    volumes:
      - ./backend/:/backend/
    command: bash -c "uvicorn backend.main:app --port 8002 --reload --host 0.0.0.0"
    ports:
      - 8002:8002
    container_name: fastapi
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    networks:
      static-network:
        ipv4_address: 172.28.1.2
  
  idom:
    image: idom:v1
    volumes:
      - ./frontend/:/frontend/
    command: bash -c "cd frontend && python3 -m run_reload.py"
    ports:
      - 8001:8001
    container_name: idom
    networks:
      static-network:
        ipv4_address: 172.28.1.1
```
frontend/config.py
```python3
base_url = "http://fastapi:8002"
```
